# Copyright (c) 2026 PayGlue by André Nünninghoff
# Licensed under the Business Source License 1.1, see LICENSE.md
# Generated by Django 5.2.12 on 2026-03-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookInboundEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_slug', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('received', 'received'), ('processing', 'processing'), ('processed', 'processed'), ('failed', 'failed'), ('dead_letter', 'dead_letter')], max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('payload_raw', models.BinaryField()),
                ('payload_snapshot', models.JSONField(blank=True, null=True)),
                ('headers_snapshot', models.JSONField(default=dict)),
                ('endpoint_path', models.CharField(max_length=255)),
                ('endpoint_token_hash', models.CharField(blank=True, default='', max_length=64)),
                ('endpoint_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('dead_lettered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='webhookeventrecord',
            new_name='webhooks_we_tenant__38a532_idx',
            old_name='webhooks_we_tenant__3e49fe_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookeventrecord',
            new_name='webhooks_we_status_36772e_idx',
            old_name='webhooks_we_status_77bc3e_idx',
        ),
        migrations.AddIndex(
            model_name='webhookinboundevent',
            index=models.Index(fields=['tenant_slug', 'provider', 'status'], name='webhooks_we_tenant__6d43d2_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookinboundevent',
            index=models.Index(fields=['status', 'next_attempt_at'], name='webhooks_we_status_1ba0ac_idx'),
        ),
    ]
