# Copyright (c) 2026 PayGlue by André Nünninghoff
# Licensed under the Business Source License 1.1, see LICENSE.md
# Generated by Django 5.2.12 on 2026-03-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_webhookinboundevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_slug', models.CharField(max_length=64)),
                ('provider_key', models.CharField(max_length=32)),
                ('enabled', models.BooleanField(default=False)),
                ('provider_type', models.CharField(max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant_slug', 'provider_key'), name='webhooks_unique_integration_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_slug', models.CharField(max_length=64)),
                ('payment_provider', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=128)),
                ('external_product_id', models.CharField(max_length=128)),
                ('entitlement_key', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=32)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['tenant_slug', 'payment_provider', 'event_type', 'is_active'], name='webhooks_pr_tenant__c747b0_idx'), models.Index(fields=['tenant_slug', 'external_product_id', 'is_active'], name='webhooks_pr_tenant__3cff07_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant_slug', 'payment_provider', 'event_type', 'external_product_id', 'entitlement_key', 'action'), name='webhooks_unique_product_mapping_rule')],
            },
        ),
    ]
