# Copyright (c) 2026 PayGlue by André Nünninghoff
# Licensed under the Business Source License 1.1, see LICENSE.md
# Generated by Django 5.2.12 on 2026-06-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_tenantprovidercredential'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantprovidercredential',
            new_name='webhooks_te_tenant__9770a6_idx',
            old_name='webhooks_te_tenant__cred_idx',
        ),
        migrations.AlterField(
            model_name='productmapping',
            name='action',
            field=models.CharField(choices=[('grant', 'grant'), ('revoke', 'revoke')], max_length=32),
        ),
    ]
