# Copyright (c) 2026 PayGlue by André Nünninghoff
# Licensed under the Business Source License 1.1, see LICENSE.md
# Generated by Django 5.2.12 on 2026-06-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0006_productmapping_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookinboundevent',
            name='status',
            field=models.CharField(choices=[('received', 'received'), ('processing', 'processing'), ('processed', 'processed'), ('skipped', 'skipped'), ('failed', 'failed'), ('dead_letter', 'dead_letter')], max_length=16),
        ),
    ]
