# Generated by Django 5.2.15 on 2026-07-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0018_split_payment_integration_config_per_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybutton',
            name='product_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buybutton',
            name='product_provider',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
