# Generated by Django 5.2.15 on 2026-07-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0019_buybutton_product_id_buybutton_product_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingtier',
            name='product_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pricingtier',
            name='product_provider',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
