# Generated by Django 5.2.15 on 2026-08-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0022_product_mapping_one_row_per_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='paywallconfig',
            name='product_provider',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
