# Generated by Django 6.1 on 2026-09-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0023_paywall_product_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingtier',
            name='cta_url_yearly',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='pricingtier',
            name='product_id_yearly',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
