# Copyright (c) 2026 PayGlue by André Nünninghoff
# Licensed under the Business Source License 1.1, see LICENSE.md
# Generated by Django 5.2.12 on 2026-03-09 20:02

import django.core.validators
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must use lowercase letters, numbers, and hyphens.', regex='^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$')]),
        ),
        migrations.AlterField(
            model_name='tenantdomain',
            name='domain',
            field=models.CharField(db_index=True, max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantdomain',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
