# Copyright (c) 2026 PayGlue by André Nünninghoff
# Licensed under the Business Source License 1.1, see LICENSE.md
# Generated by Django 5.2.12 on 2026-03-09 20:02

import django.core.validators
from django.db import migrations, models

# PG-273: this line read `django_tenants.postgresql_backend.base._check_schema_name`
# when it was generated. The package is gone, and a historical migration that
# imports a package nobody installs breaks `migrate` from zero, which is every
# fresh install and every restore drill.
#
# Safe to rewrite: a validator is Python-only and produces no DDL, so replaying
# this migration builds the same table either way. The field's current shape,
# without a validator, is recorded in the migration that follows this one.


def _check_schema_name(value):  # noqa: ARG001 - historical no-op
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, validators=[_check_schema_name]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must use lowercase letters, numbers, and hyphens.', regex='^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$')]),
        ),
        migrations.AlterField(
            model_name='tenantdomain',
            name='domain',
            field=models.CharField(db_index=True, max_length=253, unique=True),
        ),
        migrations.AlterField(
            model_name='tenantdomain',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
