# Copyright (c) 2026 PayGlue by André Nünninghoff
# Licensed under the Business Source License 1.1, see LICENSE.md
# Generated by Django 5.2.12 on 2026-03-10 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_schema_name_alter_tenant_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('billing_email', models.EmailField(blank=True, default='', max_length=254)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('tax_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PublicAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('team.member_created', 'team.member_created'), ('team.member_role_updated', 'team.member_role_updated'), ('team.member_removed', 'team.member_removed'), ('billing.profile_updated', 'billing.profile_updated'), ('integration.credentials_written', 'integration.credentials_written'), ('event.replay_requested', 'event.replay_requested')], max_length=64)),
                ('target_type', models.CharField(blank=True, default='', max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=128)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emitted_audit_events', to='tenants.tenantmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_audit_events', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'event_type', 'created_at'], name='tenants_pub_tenant__b118b4_idx')],
            },
        ),
    ]
