# Copyright (c) 2026 PayGlue by André Nünninghoff
# Licensed under the Business Source License 1.1, see LICENSE.md
# Generated by Django 5.2.12 on 2026-06-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_invitationgrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationgrant',
            name='source',
            field=models.CharField(choices=[('prefinery', 'Prefinery'), ('polar_checkout', 'Polar Checkout'), ('polar_license', 'Polar License Key'), ('manual', 'Manual')], default='prefinery', max_length=32),
        ),
        migrations.CreateModel(
            name='AccessRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('checkout', 'Checkout'), ('license_key', 'License Key')], max_length=16)),
                ('redemption_id', models.CharField(max_length=256, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['redemption_id'], name='tenants_acc_redempt_68ef37_idx')],
            },
        ),
    ]
