# Generated by Django 5.2.15 on 2026-07-07 19:47

import django.db.models.deletion
import payglue_backend.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_webhook_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicauditevent',
            name='event_type',
            field=models.CharField(choices=[('team.member_created', 'team.member_created'), ('team.member_role_updated', 'team.member_role_updated'), ('team.member_removed', 'team.member_removed'), ('billing.profile_updated', 'billing.profile_updated'), ('integration.credentials_written', 'integration.credentials_written'), ('event.replay_requested', 'event.replay_requested'), ('service_pin.generated', 'service_pin.generated'), ('service_pin.revoked', 'service_pin.revoked')], max_length=64),
        ),
        migrations.CreateModel(
            name='ServicePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=payglue_backend.tenants.models._generate_service_pin_code, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_service_pins', to='tenants.tenantmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_pins', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'expires_at'], name='tenants_ser_tenant__c92170_idx')],
            },
        ),
    ]
