# Generated by Django 5.2.15 on 2026-07-14 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_publicauditevent_event_type_servicepin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to='tenants.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['user_profile', 'consumed_at'], name='tenants_use_user_pr_d9fa99_idx')],
            },
        ),
    ]
