# Generated by Django 5.2.15 on 2026-07-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_userbackupcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationgrant',
            name='source',
            field=models.CharField(choices=[('prefinery', 'Prefinery'), ('polar_checkout', 'Polar Checkout'), ('polar_license', 'Polar License Key'), ('creem_checkout', 'Creem Checkout'), ('manual', 'Manual')], default='prefinery', max_length=32),
        ),
    ]
