# Generated by Django 5.2.15 on 2026-07-14 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_invitationgrant_license_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('solo', 'Solo'), ('studio', 'Studio'), ('agency', 'Agency'), ('founding', 'Founding Member')], max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('max_tenants', models.PositiveIntegerField(blank=True, null=True)),
                ('max_buy_buttons_per_tenant', models.PositiveIntegerField(blank=True, null=True)),
                ('max_paywalls_per_tenant', models.PositiveIntegerField(blank=True, null=True)),
                ('max_pricing_tables_per_tenant', models.PositiveIntegerField(blank=True, null=True)),
                ('max_providers_per_tenant', models.PositiveIntegerField(blank=True, null=True)),
                ('max_team_members_per_tenant', models.PositiveIntegerField(blank=True, null=True)),
                ('creem_product_id', models.CharField(blank=True, default='', max_length=64)),
                ('creem_product_id_annual', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creem_customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('creem_subscription_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_account', to='tenants.userprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_accounts', to='tenants.plan')),
            ],
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenants.billingaccount'),
        ),
    ]
