# Generated by Django 5.2.15 on 2026-07-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_alter_invitationgrant_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='downgrade_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('suspended', 'suspended'), ('disabled', 'disabled'), ('paused', 'paused')], default='active', max_length=16),
        ),
    ]
