# Generated by Django 5.2.15 on 2026-07-17 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_billingaccount_downgrade_detected_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended')], max_length=32, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Plain text. Placeholders: $email, $plan (missing/unknown placeholders are left as-is, never crash the send).')),
                ('enabled', models.BooleanField(default=True, help_text="No template, or disabled, means this trigger simply doesn't send anything -- fails safe, not loud.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='last_known_cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='last_known_subscription_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='LifecycleEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended')], max_length=32)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('billing_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_email_log', to='tenants.billingaccount')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
