# Generated by Django 5.2.15 on 2026-07-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_seed_lifecycle_email_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='admin_review_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='cancellation_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='needs_admin_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lifecycleemaillog',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lifecycleemailtemplate',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning')], max_length=32, unique=True),
        ),
    ]
