# Generated by Django 5.2.15 on 2026-07-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_seed_cancellation_reminder_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicauditevent',
            name='event_type',
            field=models.CharField(choices=[('team.member_created', 'team.member_created'), ('team.member_role_updated', 'team.member_role_updated'), ('team.member_removed', 'team.member_removed'), ('billing.profile_updated', 'billing.profile_updated'), ('integration.credentials_written', 'integration.credentials_written'), ('event.replay_requested', 'event.replay_requested'), ('connection.test_event_sent', 'connection.test_event_sent'), ('service_pin.generated', 'service_pin.generated'), ('service_pin.revoked', 'service_pin.revoked')], max_length=64),
        ),
    ]
