# Generated by Django 5.2.15 on 2026-07-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_alter_publicauditevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecycleemaillog',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning'), ('ghost_delivery_failing', 'ghost_delivery_failing')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lifecycleemailtemplate',
            name='body',
            field=models.TextField(help_text='Plain text. Placeholders depend on the trigger: the subscription triggers expose $email and $plan; ghost_delivery_failing exposes $email, $tenant and $url. Missing/unknown placeholders are left as-is, never crash the send.'),
        ),
        migrations.AlterField(
            model_name='lifecycleemailtemplate',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning'), ('ghost_delivery_failing', 'ghost_delivery_failing')], max_length=32, unique=True),
        ),
    ]
