# Generated by Django 5.2.15 on 2026-07-19 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_seed_ghost_delivery_alert_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecycleemaillog',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning'), ('ghost_delivery_failing', 'ghost_delivery_failing'), ('owner_transfer_requested', 'owner_transfer_requested')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lifecycleemailtemplate',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning'), ('ghost_delivery_failing', 'ghost_delivery_failing'), ('owner_transfer_requested', 'owner_transfer_requested')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='publicauditevent',
            name='event_type',
            field=models.CharField(choices=[('team.member_created', 'team.member_created'), ('team.member_role_updated', 'team.member_role_updated'), ('team.member_removed', 'team.member_removed'), ('billing.profile_updated', 'billing.profile_updated'), ('integration.credentials_written', 'integration.credentials_written'), ('event.replay_requested', 'event.replay_requested'), ('connection.test_event_sent', 'connection.test_event_sent'), ('service_pin.generated', 'service_pin.generated'), ('service_pin.revoked', 'service_pin.revoked'), ('team.ownership_transfer_requested', 'team.ownership_transfer_requested'), ('team.ownership_transfer_confirmed', 'team.ownership_transfer_confirmed'), ('team.ownership_transfer_rejected', 'team.ownership_transfer_rejected')], max_length=64),
        ),
        migrations.CreateModel(
            name='OwnershipTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('rejected', 'rejected'), ('cancelled', 'cancelled')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_transfers_out', to='tenants.userprofile')),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_transfers_in', to='tenants.userprofile')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_transfers_requested', to='tenants.userprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_transfers', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('tenant',), name='unique_pending_ownership_transfer_per_tenant')],
            },
        ),
    ]
