# Generated by Django 5.2.15 on 2026-07-19 12:13

import django.db.models.deletion
import payglue_backend.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0024_seed_owner_transfer_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='is_tester',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='tester_access_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invitationgrant',
            name='source',
            field=models.CharField(choices=[('prefinery', 'Prefinery'), ('polar_checkout', 'Polar Checkout'), ('polar_license', 'Polar License Key'), ('creem_checkout', 'Creem Checkout'), ('payglue_license', 'PayGlue License Code'), ('manual', 'Manual')], default='manual', max_length=32),
        ),
        migrations.CreateModel(
            name='LicenseCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=payglue_backend.tenants.models._generate_license_code, max_length=40, unique=True)),
                ('access_days', models.PositiveIntegerField(choices=[(0, 'Never expires'), (7, '7 days'), (14, '14 days'), (30, '30 days')], default=0, help_text='How long the redeeming tester keeps full access before the 30-day deletion grace period starts. 0 = never expires (permanent free tester).')),
                ('max_activations', models.PositiveIntegerField(blank=True, help_text='How many testers may redeem this code. Leave blank for unlimited.', null=True)),
                ('activation_count', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, default='', help_text='Optional note for yourself (campaign, source, etc.).', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_codes', to='tenants.plan')),
            ],
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='license_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_accounts', to='tenants.licensecode'),
        ),
        migrations.AddField(
            model_name='invitationgrant',
            name='license_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_grants', to='tenants.licensecode'),
        ),
    ]
