# Generated by Django 5.2.15 on 2026-07-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0025_billingaccount_is_tester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationgrant',
            name='creem_license_instance_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
