# Generated by Django 5.2.15 on 2026-07-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0029_alter_lifecycleemaillog_trigger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecycleemailtemplate',
            name='body',
            field=models.TextField(help_text='Plain text. Placeholders depend on the trigger: the subscription triggers expose $email and $plan; ghost_delivery_failing exposes $email, $tenant and $url; the owner_transfer_* triggers expose $tenant, $url, $new_owner and $previous_owner. Missing/unknown placeholders are left as-is, never crash the send.'),
        ),
    ]
