# Generated by Django 5.2.15 on 2026-07-20 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0030_alter_lifecycleemailtemplate_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepUpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('delete_account', 'Delete account'), ('owner_transfer', 'Confirm owner transfer')], max_length=32)),
                ('method', models.CharField(choices=[('totp', 'Authenticator app'), ('email', 'Emailed code')], max_length=16)),
                ('code_hash', models.CharField(blank=True, max_length=64)),
                ('factor_id', models.CharField(blank=True, max_length=64)),
                ('challenge_id', models.CharField(blank=True, max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_up_challenges', to='tenants.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['user_profile', 'purpose', 'consumed_at'], name='tenants_ste_user_pr_98f5dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='StepUpGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('delete_account', 'Delete account'), ('owner_transfer', 'Confirm owner transfer')], max_length=32)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_up_grants', to='tenants.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['token_hash'], name='tenants_ste_token_h_5cb993_idx')],
            },
        ),
    ]
