# Generated by Django 5.2.15 on 2026-07-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0031_stepupchallenge_stepupgrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecycleemaillog',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning'), ('ghost_delivery_failing', 'ghost_delivery_failing'), ('owner_transfer_requested', 'owner_transfer_requested'), ('owner_transfer_proposed', 'owner_transfer_proposed'), ('owner_transfer_confirmed', 'owner_transfer_confirmed'), ('owner_transfer_rejected', 'owner_transfer_rejected'), ('team_member_removed', 'team_member_removed'), ('team_member_removed_notice', 'team_member_removed_notice')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lifecycleemailtemplate',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning'), ('ghost_delivery_failing', 'ghost_delivery_failing'), ('owner_transfer_requested', 'owner_transfer_requested'), ('owner_transfer_proposed', 'owner_transfer_proposed'), ('owner_transfer_confirmed', 'owner_transfer_confirmed'), ('owner_transfer_rejected', 'owner_transfer_rejected'), ('team_member_removed', 'team_member_removed'), ('team_member_removed_notice', 'team_member_removed_notice')], max_length=32, unique=True),
        ),
    ]
