# Generated by Django 5.2.15 on 2026-07-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0036_account_deleted_backups_and_creem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecycleemaillog',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning'), ('ghost_delivery_failing', 'ghost_delivery_failing'), ('owner_transfer_requested', 'owner_transfer_requested'), ('owner_transfer_proposed', 'owner_transfer_proposed'), ('owner_transfer_confirmed', 'owner_transfer_confirmed'), ('owner_transfer_rejected', 'owner_transfer_rejected'), ('team_member_removed', 'team_member_removed'), ('team_member_removed_notice', 'team_member_removed_notice'), ('account_deleted', 'account_deleted'), ('onboarding_welcome', 'onboarding_welcome'), ('onboarding_day15', 'onboarding_day15')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lifecycleemailtemplate',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning'), ('ghost_delivery_failing', 'ghost_delivery_failing'), ('owner_transfer_requested', 'owner_transfer_requested'), ('owner_transfer_proposed', 'owner_transfer_proposed'), ('owner_transfer_confirmed', 'owner_transfer_confirmed'), ('owner_transfer_rejected', 'owner_transfer_rejected'), ('team_member_removed', 'team_member_removed'), ('team_member_removed_notice', 'team_member_removed_notice'), ('account_deleted', 'account_deleted'), ('onboarding_welcome', 'onboarding_welcome'), ('onboarding_day15', 'onboarding_day15')], max_length=32, unique=True),
        ),
        migrations.AddConstraint(
            model_name='lifecycleemaillog',
            constraint=models.UniqueConstraint(condition=models.Q(('trigger__in', ['onboarding_welcome', 'onboarding_day15'])), fields=('billing_account', 'trigger'), name='uniq_onboarding_email_per_account'),
        ),
    ]
