# Generated by Django 5.2.15 on 2026-07-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0038_seed_onboarding_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Plain text, sent through the same branded wrapper as every other PayGlue email. No placeholders: a broadcast says the same thing to everyone, which is what makes it a broadcast.')),
                ('audience', models.CharField(choices=[('all', 'Everyone with an account'), ('founding', 'Founding Member only'), ('solo', 'Solo only'), ('studio', 'Studio only'), ('agency', 'Agency only')], default='all', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
