# Generated by Django 5.2.15 on 2026-07-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0039_broadcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Off until the connection has passed a health check at least once.')),
                ('ghost_api_base_url', models.URLField(help_text='e.g. https://blog.payglue.io (no trailing path)')),
                ('ghost_admin_api_key_enc', models.TextField(blank=True, default='', help_text='Encrypted at rest, shown as dots once saved.')),
                ('creem_store_id', models.CharField(default='sto_3MX9ng1a4C6U5PVWJVbuQm', help_text='Only checkouts from this store are considered.', max_length=64)),
                ('optin_field_key', models.CharField(default='newsletteroptin', max_length=64)),
                ('ghost_email_type', models.CharField(choices=[('subscribe', 'Newsletter opt-in (double opt-in)'), ('signin', 'Magic link'), ('signup', 'Account confirmation'), ('', 'No email')], default='subscribe', max_length=16)),
                ('ghost_labels', models.CharField(default='payglue:client', help_text='Comma-separated Ghost labels, so our own customers stay filterable in the blog.', max_length=255)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_health_ok', models.BooleanField(blank=True, null=True)),
                ('last_health_detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter routing',
                'verbose_name_plural': 'Newsletter routing',
            },
        ),
    ]
