# Generated by Django 5.2.15 on 2026-07-20 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0040_newsletterrouting'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('topic', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField()),
                ('linear_issue_id', models.CharField(blank=True, max_length=64)),
                ('linear_identifier', models.CharField(blank=True, db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Resolved'), ('cancelled', 'Closed')], default='open', max_length=20)),
                ('status_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='tenants_sup_tenant__313871_idx')],
            },
        ),
    ]
