# Generated by Django 5.2.15 on 2026-07-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0041_supportrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundingSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128, unique=True)),
                ('product_id', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tier', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
