# Generated by Django 5.2.15 on 2026-07-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0042_foundingsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='founding_price_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='founding_tier',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foundingsale',
            name='price_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foundingsale',
            name='tier_was_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
