# Generated by Django 5.2.15 on 2026-08-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0044_local_credentials_on_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_first_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('is_first_account', True)), fields=('is_first_account',), name='only_one_bootstrap_account'),
        ),
    ]
