# Generated by Django 5.2.15 on 2026-08-10 12:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0045_only_one_bootstrap_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=40)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('done', 'Shipped'), ('in-progress', 'In progress'), ('pivot', 'Pivot'), ('reconsidered', 'Reconsidered'), ('wont-build', "Won't build")], default='done', max_length=20)),
                ('badge', models.CharField(blank=True, max_length=40)),
                ('meta', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('items', models.JSONField(blank=True, default=list)),
                ('show_in_bell', models.BooleanField(default=False)),
                ('bell_body', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Changelog entries',
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
