# Generated by Django 5.2.16 on 2026-08-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0047_rename_support_linear_to_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Pending'), ('in_progress', 'Active'), ('done', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
