# Generated by Django 5.2.16 on 2026-08-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0048_support_status_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='subject',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
