# Generated by Django 5.2.16 on 2026-08-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0049_support_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='account_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
