# Generated by Django 6.1 on 2026-09-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0051_alter_tenant_schema_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaccount',
            name='lapsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingaccount',
            name='payment_failed_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitationgrant',
            name='creem_customer_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='invitationgrant',
            name='creem_subscription_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='lifecycleemaillog',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning'), ('payment_failed', 'payment_failed'), ('payment_failed_reminder', 'payment_failed_reminder'), ('access_paused', 'access_paused'), ('ghost_delivery_failing', 'ghost_delivery_failing'), ('owner_transfer_requested', 'owner_transfer_requested'), ('owner_transfer_proposed', 'owner_transfer_proposed'), ('owner_transfer_confirmed', 'owner_transfer_confirmed'), ('owner_transfer_rejected', 'owner_transfer_rejected'), ('team_member_removed', 'team_member_removed'), ('team_member_removed_notice', 'team_member_removed_notice'), ('account_deleted', 'account_deleted'), ('onboarding_welcome', 'onboarding_welcome'), ('onboarding_day15', 'onboarding_day15')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lifecycleemailtemplate',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning'), ('payment_failed', 'payment_failed'), ('payment_failed_reminder', 'payment_failed_reminder'), ('access_paused', 'access_paused'), ('ghost_delivery_failing', 'ghost_delivery_failing'), ('owner_transfer_requested', 'owner_transfer_requested'), ('owner_transfer_proposed', 'owner_transfer_proposed'), ('owner_transfer_confirmed', 'owner_transfer_confirmed'), ('owner_transfer_rejected', 'owner_transfer_rejected'), ('team_member_removed', 'team_member_removed'), ('team_member_removed_notice', 'team_member_removed_notice'), ('account_deleted', 'account_deleted'), ('onboarding_welcome', 'onboarding_welcome'), ('onboarding_day15', 'onboarding_day15')], max_length=32, unique=True),
        ),
    ]
