# Generated by Django 6.1 on 2026-09-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0053_seed_lapse_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecycleemaillog',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning'), ('payment_failed', 'payment_failed'), ('payment_failed_reminder', 'payment_failed_reminder'), ('access_paused', 'access_paused'), ('deletion_notice', 'deletion_notice'), ('inactive_account_deleted', 'inactive_account_deleted'), ('ghost_delivery_failing', 'ghost_delivery_failing'), ('owner_transfer_requested', 'owner_transfer_requested'), ('owner_transfer_proposed', 'owner_transfer_proposed'), ('owner_transfer_confirmed', 'owner_transfer_confirmed'), ('owner_transfer_rejected', 'owner_transfer_rejected'), ('team_member_removed', 'team_member_removed'), ('team_member_removed_notice', 'team_member_removed_notice'), ('account_deleted', 'account_deleted'), ('onboarding_welcome', 'onboarding_welcome'), ('onboarding_day15', 'onboarding_day15')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lifecycleemailtemplate',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning'), ('payment_failed', 'payment_failed'), ('payment_failed_reminder', 'payment_failed_reminder'), ('access_paused', 'access_paused'), ('deletion_notice', 'deletion_notice'), ('inactive_account_deleted', 'inactive_account_deleted'), ('ghost_delivery_failing', 'ghost_delivery_failing'), ('owner_transfer_requested', 'owner_transfer_requested'), ('owner_transfer_proposed', 'owner_transfer_proposed'), ('owner_transfer_confirmed', 'owner_transfer_confirmed'), ('owner_transfer_rejected', 'owner_transfer_rejected'), ('team_member_removed', 'team_member_removed'), ('team_member_removed_notice', 'team_member_removed_notice'), ('account_deleted', 'account_deleted'), ('onboarding_welcome', 'onboarding_welcome'), ('onboarding_day15', 'onboarding_day15')], max_length=32, unique=True),
        ),
    ]
