# Copyright (c) 2026 PayGlue by André Nünninghoff
# Licensed under the Business Source License 1.1, see LICENSE.md
"""PG-319: the delivery alert fires from the worker and knows two causes.

Adds the provider_webhook_failing trigger and seeds it ENABLED, like the
Ghost alert before it (0022): the alert is the point, it has to work out of
the box. Rewrites the ghost_delivery_failing copy where it is still the
0027 wording, because that text promised an automatic re-delivery that does
not exist (after five attempts an event needs Replay) and did not carry the
count and date the new sender supplies. A template someone edited in the
admin is left alone.
"""
# Generated by Django 6.1 on 2026-09-13 13:06

from django.db import migrations, models


_SIGN_OFF = "__\nCheers,\nPayGlue - Team"

PROVIDER_TRIGGER = "provider_webhook_failing"
PROVIDER_SUBJECT = "PayGlue: $provider webhooks for $tenant are being rejected"
PROVIDER_BODY = (
    "Hi,\n\n"
    "$provider is sending purchase events for $tenant, but PayGlue cannot verify "
    "them. $count event(s) since $since were rejected, and those buyers have not "
    "been unlocked in Ghost yet.\n\n"
    "The usual cause is a webhook secret that does not match: the secret saved in "
    "PayGlue is not the one $provider uses for this endpoint. Please compare both "
    "here:\n"
    "$url\n\n"
    "If the secrets match and events keep failing, the problem is on our side. "
    "Reply to this mail and we will look at it the same day. The failed events "
    "stay in your event log and can be replayed once the cause is fixed, so no "
    "purchase is lost.\n\n" + _SIGN_OFF
)

GHOST_TRIGGER = "ghost_delivery_failing"
GHOST_SUBJECT = "PayGlue: Your Ghost connection is failing"
GHOST_BODY = (
    "Hi,\n\n"
    "Access delivery to your Ghost site ($tenant) is failing. $count purchase "
    "event(s) since $since could not be delivered, so those buyers have not been "
    "unlocked in Ghost yet.\n\n"
    "Most common causes: your Ghost Admin API key was rotated or has expired, or "
    "your Ghost site is temporarily unreachable.\n\n"
    "Please check your Ghost connection in PayGlue:\n"
    "$url\n\n"
    "There you can update the credentials and run the health check. Once the "
    "connection works again, open the event log and use Replay on the failed "
    "events, or reply to this mail and we do it for you. No purchase is lost, "
    "the events stay in your log.\n\n" + _SIGN_OFF
)
# The 0027 wording is recognised by this sentence; an edited template does not
# contain it and is left as the admin wrote it.
_OLD_GHOST_MARKER = "pending events are re-delivered automatically"


def seed(apps, schema_editor):
    Template = apps.get_model("tenants", "LifecycleEmailTemplate")
    Template.objects.get_or_create(
        trigger=PROVIDER_TRIGGER,
        defaults={"subject": PROVIDER_SUBJECT, "body": PROVIDER_BODY, "enabled": True},
    )
    Template.objects.filter(
        trigger=GHOST_TRIGGER, body__contains=_OLD_GHOST_MARKER
    ).update(subject=GHOST_SUBJECT, body=GHOST_BODY)


def unseed(apps, schema_editor):
    Template = apps.get_model("tenants", "LifecycleEmailTemplate")
    Template.objects.filter(trigger=PROVIDER_TRIGGER).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0055_seed_deletion_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecycleemaillog',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning'), ('payment_failed', 'payment_failed'), ('payment_failed_reminder', 'payment_failed_reminder'), ('access_paused', 'access_paused'), ('deletion_notice', 'deletion_notice'), ('inactive_account_deleted', 'inactive_account_deleted'), ('ghost_delivery_failing', 'ghost_delivery_failing'), ('provider_webhook_failing', 'provider_webhook_failing'), ('owner_transfer_requested', 'owner_transfer_requested'), ('owner_transfer_proposed', 'owner_transfer_proposed'), ('owner_transfer_confirmed', 'owner_transfer_confirmed'), ('owner_transfer_rejected', 'owner_transfer_rejected'), ('team_member_removed', 'team_member_removed'), ('team_member_removed_notice', 'team_member_removed_notice'), ('account_deleted', 'account_deleted'), ('onboarding_welcome', 'onboarding_welcome'), ('onboarding_day15', 'onboarding_day15')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lifecycleemailtemplate',
            name='body',
            field=models.TextField(help_text='Plain text. Placeholders depend on the trigger: the subscription triggers expose $email and $plan; ghost_delivery_failing and provider_webhook_failing expose $email, $tenant, $url, $provider, $count and $since; the owner_transfer_* triggers expose $tenant, $url, $new_owner and $previous_owner. Missing/unknown placeholders are left as-is, never crash the send.'),
        ),
        migrations.AlterField(
            model_name='lifecycleemailtemplate',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning'), ('payment_failed', 'payment_failed'), ('payment_failed_reminder', 'payment_failed_reminder'), ('access_paused', 'access_paused'), ('deletion_notice', 'deletion_notice'), ('inactive_account_deleted', 'inactive_account_deleted'), ('ghost_delivery_failing', 'ghost_delivery_failing'), ('provider_webhook_failing', 'provider_webhook_failing'), ('owner_transfer_requested', 'owner_transfer_requested'), ('owner_transfer_proposed', 'owner_transfer_proposed'), ('owner_transfer_confirmed', 'owner_transfer_confirmed'), ('owner_transfer_rejected', 'owner_transfer_rejected'), ('team_member_removed', 'team_member_removed'), ('team_member_removed_notice', 'team_member_removed_notice'), ('account_deleted', 'account_deleted'), ('onboarding_welcome', 'onboarding_welcome'), ('onboarding_day15', 'onboarding_day15')], max_length=32, unique=True),
        ),
        migrations.RunPython(seed, unseed),
    ]
