# Copyright (c) 2026 PayGlue by André Nünninghoff
# Licensed under the Business Source License 1.1, see LICENSE.md
"""PG-327: two templates for sub-processor notices.

subprocessor_added and subprocessor_removed are not fired by any event. The
operator turns one into a Broadcast draft from the admin. They are seeded so
the text sits next to every other mail and can be edited there. A template
somebody already created or edited is left alone.
"""
# Generated by Django 6.1 on 2026-09-30 12:07

from django.db import migrations, models


_SIGN_OFF = "__\nCheers,\nPayGlue - Team"

ADDED_SUBJECT = "PayGlue: a new sub-processor, $name, from $effective_date"
ADDED_BODY = (
    "Hi,\n\n"
    "we are writing to tell you about a change to the sub-processors PayGlue "
    "uses to process data on your behalf.\n\n"
    "We plan to add $name as a new sub-processor.\n\n"
    "Sub-processor: $name\n"
    "Purpose: $purpose\n"
    "Processing location: $location\n"
    "Website: $website\n"
    "Starts processing on: $effective_date\n\n"
    "The complete and current list, with the full change history, is here:\n"
    "$url\n\n"
    "Your right to object\n\n"
    "Under section 8 of our Data Processing Agreement you may object to a new "
    "sub-processor. If you have reasonable data-protection grounds against "
    "$name, reply to this mail before $effective_date. We will look at your "
    "concern together with you and try to find a solution. If we cannot find "
    "one, you may terminate the affected part of the service.\n\n"
    "If we do not hear from you by then, we will take it that you agree to the "
    "change. Nothing changes in how you use PayGlue, and you do not need to do "
    "anything.\n\n"
    "Questions? Just reply, this mail reaches a person.\n\n" + _SIGN_OFF
)

REMOVED_SUBJECT = "PayGlue: $name is no longer a sub-processor"
REMOVED_BODY = (
    "Hi,\n\n"
    "a short notice about the sub-processors PayGlue uses to process data on "
    "your behalf.\n\n"
    "$name is no longer a sub-processor as of $effective_date.\n\n"
    "Sub-processor: $name\n"
    "What it did: $purpose\n\n"
    "One company fewer processes data for you now, so there is nothing to "
    "object to and nothing you need to do. We tell you anyway, because we keep "
    "you informed about every change to that list, removals included.\n\n"
    "The complete and current list, with the full change history, is here:\n"
    "$url\n\n" + _SIGN_OFF
)


def seed(apps, schema_editor):
    Template = apps.get_model("tenants", "LifecycleEmailTemplate")
    Template.objects.get_or_create(
        trigger="subprocessor_added",
        defaults={"subject": ADDED_SUBJECT, "body": ADDED_BODY, "enabled": True},
    )
    Template.objects.get_or_create(
        trigger="subprocessor_removed",
        defaults={"subject": REMOVED_SUBJECT, "body": REMOVED_BODY, "enabled": True},
    )


def unseed(apps, schema_editor):
    Template = apps.get_model("tenants", "LifecycleEmailTemplate")
    Template.objects.filter(
        trigger__in=["subprocessor_added", "subprocessor_removed"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0056_pg319_provider_webhook_failing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecycleemaillog',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning'), ('payment_failed', 'payment_failed'), ('payment_failed_reminder', 'payment_failed_reminder'), ('access_paused', 'access_paused'), ('deletion_notice', 'deletion_notice'), ('inactive_account_deleted', 'inactive_account_deleted'), ('ghost_delivery_failing', 'ghost_delivery_failing'), ('provider_webhook_failing', 'provider_webhook_failing'), ('owner_transfer_requested', 'owner_transfer_requested'), ('owner_transfer_proposed', 'owner_transfer_proposed'), ('owner_transfer_confirmed', 'owner_transfer_confirmed'), ('owner_transfer_rejected', 'owner_transfer_rejected'), ('team_member_removed', 'team_member_removed'), ('team_member_removed_notice', 'team_member_removed_notice'), ('account_deleted', 'account_deleted'), ('subprocessor_added', 'subprocessor_added'), ('subprocessor_removed', 'subprocessor_removed'), ('onboarding_welcome', 'onboarding_welcome'), ('onboarding_day15', 'onboarding_day15')], max_length=32),
        ),
        migrations.AlterField(
            model_name='lifecycleemailtemplate',
            name='body',
            field=models.TextField(help_text='Plain text. Placeholders depend on the trigger: the subscription triggers expose $email and $plan; ghost_delivery_failing and provider_webhook_failing expose $email, $tenant, $url, $provider, $count and $since; the owner_transfer_* triggers expose $tenant, $url, $new_owner and $previous_owner; the subprocessor_* triggers expose $name, $purpose, $location, $website, $effective_date and $url (the public sub-processor list). Missing/unknown placeholders are left as-is, never crash the send.'),
        ),
        migrations.AlterField(
            model_name='lifecycleemailtemplate',
            name='trigger',
            field=models.CharField(choices=[('downgrade', 'downgrade'), ('scheduled_cancellation', 'scheduled_cancellation'), ('subscription_ended', 'subscription_ended'), ('cancellation_reminder_15d', 'cancellation_reminder_15d'), ('cancellation_final_warning', 'cancellation_final_warning'), ('payment_failed', 'payment_failed'), ('payment_failed_reminder', 'payment_failed_reminder'), ('access_paused', 'access_paused'), ('deletion_notice', 'deletion_notice'), ('inactive_account_deleted', 'inactive_account_deleted'), ('ghost_delivery_failing', 'ghost_delivery_failing'), ('provider_webhook_failing', 'provider_webhook_failing'), ('owner_transfer_requested', 'owner_transfer_requested'), ('owner_transfer_proposed', 'owner_transfer_proposed'), ('owner_transfer_confirmed', 'owner_transfer_confirmed'), ('owner_transfer_rejected', 'owner_transfer_rejected'), ('team_member_removed', 'team_member_removed'), ('team_member_removed_notice', 'team_member_removed_notice'), ('account_deleted', 'account_deleted'), ('subprocessor_added', 'subprocessor_added'), ('subprocessor_removed', 'subprocessor_removed'), ('onboarding_welcome', 'onboarding_welcome'), ('onboarding_day15', 'onboarding_day15')], max_length=32, unique=True),
        ),
        migrations.RunPython(seed, unseed),
    ]
